import 'package:flutter/material.dart';
import 'package:sizer/sizer.dart';
import '../../theme/app_theme.dart';
import '../../widgets/visual_effects.dart';

class TipsSectionScreen extends StatefulWidget {
  const TipsSectionScreen({Key? key}) : super(key: key);

  @override
  _TipsSectionScreenState createState() => _TipsSectionScreenState();
}

class _TipsSectionScreenState extends State<TipsSectionScreen> {
  final TextEditingController _searchController = TextEditingController();
  final List<Map<String, dynamic>> _allTips = [
    {
      'title': 'Carbon Footprint 101',
      'subtitle': 'Understanding the basics of your impact.',
      'details': 'Your carbon footprint is the total amount of greenhouse gases (including carbon dioxide and methane) that are generated by your actions.\n\nAverage footprint for people in United States is 16 tons, one of the highest rates in the world. Globally, the average is closer to 4 tons.',
      'color': AppTheme.skyBlue,
      'icon': Icons.school,
    },
    {
      'title': 'Climate Effects',
      'subtitle': 'How rising temperatures change our world.',
      'details': 'Global warming stresses ecosystems through temperature rises, water shortages, increased fire threats, drought, weed and pest invasions, intense storm damage and salt invasion.',
      'color': AppTheme.fireOrange,
      'icon': Icons.public,
    },
    {
      'title': 'Reduce, Reuse, Recycle',
      'subtitle': 'Simple steps to minimize waste daily.',
      'details': 'Reduce: Don\'t buy what you don\'t need.\nReuse: Switch to reusable bags, bottles, and straws.\nRecycle: Sort your waste correctly to ensure materials can be processed.',
      'color': AppTheme.ecoGreen,
      'icon': Icons.recycling,
    },
    {
      'title': 'Energy Efficiency',
      'subtitle': 'Saving power saves the planet (and money!).',
      'details': 'Switching to LED bulbs, using smart thermostats, and unplugging electronics when not in use can significantly reduce your energy consumption.',
      'color': AppTheme.rubberDuckYellow,
      'icon': Icons.lightbulb,
    },
     {
      'title': 'Water Conservation',
      'subtitle': 'Every drop counts.',
      'details': 'Fix leaks, take shorter showers, and turn off the tap while brushing your teeth.',
      'color': AppTheme.skyBlue,
      'icon': Icons.water_drop,
    },
  ];

  List<Map<String, dynamic>> _filteredTips = [];

  @override
  void initState() {
    super.initState();
    _filteredTips = _allTips;
    _searchController.addListener(_onSearchChanged);
  }

  void _onSearchChanged() {
    setState(() {
      _filteredTips = _allTips.where((tip) {
        final query = _searchController.text.toLowerCase();
        return tip['title'].toLowerCase().contains(query) || 
               tip['subtitle'].toLowerCase().contains(query);
      }).toList();
    });
  }

  @override
  void dispose() {
    _searchController.dispose();
    super.dispose();
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Eco-Guide')),
      body: Column(
        children: [
          Padding(
            padding: EdgeInsets.all(4.w),
            child: FadeInSlide(
              child: TextField(
                controller: _searchController,
                decoration: InputDecoration(
                  hintText: 'Search topics...',
                  prefixIcon: Icon(Icons.search),
                  filled: true,
                  fillColor: AppTheme.featherWhite,
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(16),
                    borderSide: BorderSide.none,
                  ),
                  contentPadding: EdgeInsets.symmetric(horizontal: 4.w, vertical: 2.h),
                ),
              ),
            ),
          ),
          Expanded(
            child: ListView.builder(
              padding: EdgeInsets.symmetric(horizontal: 4.w, vertical: 2.h),
              itemCount: _filteredTips.length,
              itemBuilder: (context, index) {
                final tip = _filteredTips[index];
                return _buildTipCard(
                  context,
                  tip['title'],
                  tip['subtitle'],
                  tip['details'],
                  tip['color'],
                  tip['icon'],
                  100 + (index * 100),
                );
              },
            ),
          ),
        ],
      ),
    );
  }

  Widget _buildTipCard(
    BuildContext context,
    String title,
    String subtitle,
    String details,
    Color color,
    IconData icon,
    int delay,
  ) {
    return FadeInSlide(
      delay: Duration(milliseconds: delay),
      child: Card(
        margin: EdgeInsets.only(bottom: 2.h),
        child: Theme(
          data: Theme.of(context).copyWith(dividerColor: Colors.transparent),
          child: ExpansionTile(
            tilePadding: EdgeInsets.all(3.w),
            childrenPadding: EdgeInsets.fromLTRB(4.w, 0, 4.w, 4.w),
            leading: Container(
              padding: EdgeInsets.all(3.w),
              decoration: BoxDecoration(
                color: color.withValues(alpha: 0.1),
                borderRadius: BorderRadius.circular(12),
              ),
              child: Icon(icon, color: color, size: 24.sp),
            ),
            title: Text(
              title,
              style: Theme.of(context).textTheme.titleLarge?.copyWith(fontSize: 14.sp),
            ),
            subtitle: Text(
              subtitle,
              style: Theme.of(context).textTheme.bodyMedium?.copyWith(fontSize: 11.sp),
            ),
            children: [
              Text(
                details,
                style: TextStyle(color: AppTheme.wolfGray, height: 1.5, fontSize: 12.sp),
              ),
            ],
          ),
        ),
      ),
    );
  }
}
